### ISSUE TITLE
네모의 꿈 레이아웃, 메뉴 노출 대상 권한 '관리자만' 선택시 문제

### ISSUE THREAD

**Issue by alrin1** [rhymix/rhymix-simple-world#1]
![untitled-1](https://user-images.githubusercontent.com/17227410/46976875-9767bd00-d105-11e8-9a85-aea68de5a822.jpg)

사이트 메뉴 편집 - 권한 - 메뉴 노출 대상에서 '관리자만' 선택시 
하위 메뉴가 있으면 그림처럼 비로그인 상태에서 노출됩니다.
하위 메뉴가 없으면 뜨지 않습니다.

**Comment by misol** [comment]
늦었지만, 수정되었습니다.
