### ISSUE TITLE
브라우저 설정에 따라 다크모드/라이트 모드 자동 전환 가능한 옵션 추가

### ISSUE THREAD

**Issue by misol** [rhymix/rhymix-simple-world#2]
최근 브라우저/OS가 다크모드를 적극 채용하고 있습니다.
운영체제나 브라우저에서 다크모드 설정 값이 있을 경우 이를 따를 수 있게 합니다.

**Comment by kijin** [comment]
다크모드 사용 여부를 가장 정확하고 안정적으로 감지할 수 있는 방법에는 무엇이 있을까요?

스킨과 레이아웃들이 각자도생하기보다는 코어에서 "지금 다크모드임"이라는 의미의 변수를 하나 제공하면 CSS뿐 아니라 HTML 템플릿에서도 참조할 수 있게 되어 편리할 것 같거든요.

**Comment by misol** [comment]
> 다크모드 사용 여부를 가장 정확하고 안정적으로 감지할 수 있는 방법에는 무엇이 있을까요?
> 
> 스킨과 레이아웃들이 각자도생하기보다는 코어에서 "지금 다크모드임"이라는 의미의 변수를 하나 제공하면 CSS뿐 아니라 HTML 템플릿에서도 참조할 수 있게 되어 편리할 것 같거든요.

브라우저 단에서 브라우저가 (또는 운영체제가) 다크모드로 설정되어 있는지 알려주는 변수는 확실히 있습니다. 다만, 지원하지 않는 브라우저도 많기 때문에 이를 고려해야 합니다. ( https://medium.com/@daelity/웹페이지에서-dark-mode-감지하기-81526e0a0c7a ) 레이아웃이나 스킨끼리의 의사소통은 쿠키나 세션값으로 표준을 정하는 쪽이 나을 것 같습니다.
라이믹스 기본 레이아웃이나 스킨에서 기준을 하나 정해서 미는 방법도 생각해볼 수 있을 것 같습니다.
스킨/레이아웃 info.xml에 다크모드 호환성 여부를 표시해두게 하고 이를 라이믹스 코어 단에서 각 레이아웃이나 스킨에 현재 페이지에 적용된 모든 스킨이나 레이아웃이 다크모드에 호환성이 있는지 알려주는 방법이 있겠습니다.

**Comment by bjrambo** [comment]
@misol 사이트에서 다크모드의 경우 갑작스럽게 적용하게 되면 굉장히 부정적인 이미지를 주어질 수 있습니다.

XETown의 예시만 봐도 호불호가 너무 갈리는 문제가 있었지요.

따라서 라이믹스에서 제공해주는것보다 각 레이아웃 스킨에서 다크모드를 선택적으로 주어지도록 해주는것이 좀 더 나을 것 같아요.

**Comment by misol** [comment]
@bjrambo 기능을 활성화 할지에 대해서는 관리자에게 당연히 선택권을 줍니다만, 제 고민은 다크모드가 활성화된 사이트에서 레이아웃과 스킨 사이의 정보 교환 문제입니다

**Comment by bjrambo** [comment]
굳이 코어에 그런 정보를 교환할 수 잇도록 제공할 필요가 있을까요?

어차피 브라우저에서 가져오는 값은 javascript에서 처리가 가능할 것이고 그 부분을 담당하는 부분은 레이아웃만으로도 가능할 것 같아서요...

**Comment by bjrambo** [comment]
아 라이믹스 코어가 아니였군요 제가 착각했습니다. 죄송합니다 (ㅠㅠ)

**Comment by misol** [comment]
@bjrambo 브라우저나 운영체제가 다크모드를 선호하는지 여부는 javascript나 CSS로 처리가 가능하지만, 한 페이지에서 같이 사용되는 스킨이나 레이아웃이 다크모드 스타일을 지원하고 있는지는 라이믹스 코어에서 표준을 정해줄 필요가 있을 것 같다는 생각은 듭니다. 일단 이 이슈에서는 현재 널리 사용되는 라이믹스 스킨/레이아웃에서 사용하는 표준을 조금 살펴보고 코어 수정 없이, 최대한 호환성을 맞추려고 합니다.

쿠키나 세션으로 정보교환을 하면 될 것 같아서 코어가 개입하지 않고도 "사실상의 표준"이 정해지면 큰 문제는 없을 것 같다는 생각도 듭니다.

**Comment by misol** [comment]
완료
