### ISSUE TITLE
회원가입 스킨 스크롤 기능이 있어야할것 같습니다.

### ISSUE THREAD

**Issue by jominhyun** [rhymix/rhymix-simple-world#5]
![123132](https://user-images.githubusercontent.com/13338225/106374099-2c6c4e00-63c3-11eb-8420-d3b9189de637.PNG)

약관의 내용이 많을 경우 마우스로 스크롤을 해야 가입 폼이 보입니다.
아래 사진 기본스킨처럼 창 크기를 줄여 스크롤로 볼수 있었으면 합니다.

 
![1231233](https://user-images.githubusercontent.com/13338225/106374126-71908000-63c3-11eb-9038-627150084a86.PNG)

**Comment by misol** [comment]
적용해보겠습니다 :)
업데이트가 있으면 이 스레드에 추가로 알려드리겠습니다.

**Comment by jominhyun** [comment]
> 적용해보겠습니다 :)
> 업데이트가 있으면 이 스레드에 추가로 알려드리겠습니다.

제 의견을 반영해주신다니 감사합니다.

**Comment by misol** [comment]
해결한 버전을 배포했습니다. (https://github.com/rhymix/rhymix-simple-world/releases/tag/0.3.2)
